---

- hosts: masters
  become: yes
  vars_prompt:
    - name: "add_nodes"
      prompt: "Which nodes would you like to setup?(format: <Hostname:IP:Node type>,...)"
      private: no
  tasks:
    - add_host:
        name: "{{ item.split(':')[1] }}"
        groups: "{{ item.split(':')[2] }},add_hosts"
        node_type: "{{ item.split(':')[2] }}"
      with_items: "{{ add_nodes.split(',') }}"
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true

    - name: Split nodes by node type
      add_host:
        name: "{{ item }}"
        groups: "add_{{ hostvars['' + item].node_type }}"
      with_items: "{{ groups['add_hosts'] }}"
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true

- hosts: masters
  become: yes
  roles:
    - { role: gen-certs, tags: gen-certs }

- hosts: add_hosts
  become: yes
  tasks:
    - name: Split nodes by node type
      add_host:
        name: "{{ item }}"
        groups: "add_{{ hostvars['' + item].node_type }}"
      with_items: "{{ groups['add_hosts'] }}"

- hosts: add_hosts
  become: yes
  roles:
    - { role: cri/docker,     when: cri_plugin == 'docker', tags: docker }
    - { role: cri/containerd, when: cri_plugin == 'containerd', tags: containerd }

- hosts: add_masters
  become: yes
  roles:
    - { role: kubernetes/gen-configs, node_role: "master", tags: master-gen-config }
    - { role: kubernetes/ha, tags: ha }
    - { role: kubernetes/master, tags: master }

- hosts: add_nodes
  become: yes
  roles:
    - { role: kubernetes/gen-configs, node_role: "node", tags: master-gen-config }
    - { role: kubernetes/node, tags: node }

- hosts: masters
  become: yes
  roles:
    - { role: kubernetes/approve-certs, tags: approve-certs }

- hosts: kube-cluster
  become: yes
  roles:
    - { role: cri/checker, when: cri_plugin == 'containerd', tags: checker }
