---
# Tear down nodes

- hosts: masters
  become: yes
  vars_prompt:
    - name: "del_nodes"
      prompt: "Which nodes would you like to delete?(format: <Hostname:IP>,...)"
      private: no
  roles:
    - { role: ops/del-node, tags: del-node }
  tasks:
    - add_host:
        name: "{{ item.split(':')[1] }}"
        groups: "del_hosts"
      with_items: "{{ del_nodes.split(',') }}"

- hosts: del_hosts
  become: yes
  roles:
    - { role: ops/reset , reset_kubernetes: true }
