---

keepalived_check_ip: any
keepalived_check_port: 2379
keepalived_check_vid: 53
keepalived_check_vmask: 24

haproxy_etc_dir: /etc/haproxy
haproxy_admin_port: 9090
haproxy_admin_user: admin
haproxy_admin_passwd: admin123
