---

- name: Adding Ceph APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: "https://download.ceph.com/keys/release.asc"
    state: present

- name: Adding Ceph APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: "deb https://download.ceph.com/debian-{{ ceph_version }}/ xenial main"
    state: present
    filename: 'ceph'

- name: Adding Ceph yum repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: "ceph-{{ ceph_version }}"
    description: Ceph Repository
    file: ceph
    baseurl: "https://download.ceph.com/rpm-{{ ceph_version }}/el7/x86_64"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.ceph.com/keys/release.asc

- name: Install Ceph packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum: name=ceph state=present

- name: Install Ceph packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt: name=ceph state=present

- name: Update dns resolv conf for Ceph
  template: src="resolv.conf.j2" dest="/etc/resolv.conf"
