---

- name: Install Ceph dependency packages
  include_tasks: install-ceph.yml

- name: Create and copy generator config file
  include_tasks: gen-config.yml
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Deploy Ceph components on Kubernetes
  include_tasks: ceph-on-k8s.yml
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

# - name: Label all storage nodes
#   shell: "kubectl label nodes node-type=storage"
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   ignore_errors: true
