---

# Kubenrtes version, only support 1.7.0+.
kube_version: 1.9.0

# CRI plugin,
# Supported: docker, containerd.
cri_plugin: docker

# CNI plugin,
# Supported: calico, flannel, weave, canal or router.
network: calico
pod_network_cidr: 10.244.0.0/16

# CNI opts,
# flannel(--iface=enp0s8), calico(interface=enp0s8), canal(enp0s8).
cni_iface: ""

# Kubernetes cluster network.
cluster_subnet: 10.96.0
kubernetes_service_ip: "{{ cluster_subnet }}.1"
service_ip_range: "{{ cluster_subnet }}.0/12"
service_node_port_range: 30000-32767
api_secure_port: 5443

# Highly Available configuration.
haproxy: true
keepalived: true # set `lb_vip_address` as keepalived vip, if this enable.
keepalived_vip_interface: "{{ ansible_default_ipv4.interface }}"

lb_vip_address: 172.16.35.9
lb_secure_port: 6443
lb_api_url: "https://{{ lb_vip_address }}:{{ lb_secure_port }}"

# Etcd configuration variables.
etcd_initial_token: etcd-k8s-cluster
etcd_domain_name: test.etcd.com
etcd_iface: ""

# A list of insecure registrys you might need to define
add_registry:
# - "gcr.io"

insecure_registrys:
# - "172.16.35.9:5000"

# Kubernetes authentication and security
bootstrap_token: b96cee11d16de85256d63efd2e18e7d8
extra_auth:
  basic:
    accounts:
    - 'p@ssw0rd,admin,admin'
  # token:
  #   values:
  #   - "0fdd1a8875ec,admin,admin"

encryption_token: iTNwwjHuxNI9+8niwh8GJKT5NQiHFqcOTrrhzYfhAvk=

# Core addons (Strongly recommend)
kube_dns: true
dns_name: cluster.local # cluster dns name
dns_ip: "{{ cluster_subnet }}.10"

kube_proxy: true
kube_proxy_mode: iptables # support: iptables, userspace or ipvs(alpha).
kube_proxy_ipvs_scheduler: rr # depend on ipvs mode.

# Extra addons
kube_dashboard: false
kube_logging: false
kube_monitoring: false

ingress: false
ingress_type: nginx # support: nginx or traefik.

# Extra storage
registry: false
registry_ui: false
registry_url: "172.16.35.9:5000"

ceph_cluster: false

# Offline mode area
repos_offline: false
repos_port: 4040
repos_offline_url: "http://172.16.35.9:{{ repos_port }}"
