#!/bin/bash -v
# install git
sudo yum install -y git

# install Ansible
sudo yum install -y ansible

# install Vagrant
sudo wget https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.rpm?_ga=2.266151311.1084437012.1514875446-738854030.1514875446
sudo mv vagrant_2.0.1_x86_64.rpm?_ga=2.266151311.1084437012.1514875446-738854030.1514875446 vagrant2.0.1.rpm
sudo rpm -ivh vagrant2.0.1.rpm

# install VirtualBox
sudo yum install -y gcc
sudo yum install -y kernel-devel
sudo wget http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
sudo mv virtualbox.repo /etc/yum.repos.d/
sudo yum -y install VirtualBox-5.2

# install docker
curl -fsSL "https://get.docker.com/" | sh

# install docker-machine
base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine
