#!/bin/bash -v
# install git
sudo yum install -y git

# install Ansible
sudo yum install -y ansible

# install Vagrant 
sudo wget https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.rpm?_ga=2.266151311.1084437012.1514875446-738854030.1514875446
sudo mv vagrant_2.0.1_x86_64.rpm?_ga=2.266151311.1084437012.1514875446-738854030.1514875446 vagrant2.0.1.rmp
sudo rpm -ivh vagrant_2.0.1.rpm

# install VirtualBox
sudo yum install -y gcc
sudo yum install -y kernel-devel
sudo wget http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
sudo mv virtualbox.repo /etc/yum.repos.d/
sudo yum -y install VirtualBox-5.2

# install docker
curl -fsSL "https://get.docker.com/" | sh

# clone all repos
cd ~
git clone https://github.com/acinwinstack/chimichanga.git

# deploy minikube
cd ~
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ~/kubectl
sudo mv ~/kubectl /usr/local/bin/kubectl
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
minikube start
minikube stop

# deploy k8s manual installation lab nodes
cd ~/chimichanga/k8s-manual
vagrant up
vagrant halt

# deploy k8s kubeadm installation lab nodes
cd ~/chimichanga/k8s-kubeadm
vagrant up
vagrant halt

## deploy docker-registry node
cd ~/chimichanga/docker-registry
vagrant up

## vagrant ssh
## pull necessary images
#### docker pull python
#### docker pull redis
#### docker pull mongodb
#### docker pull nginx

vagrant halt





# deploy k8s lab nodes
#cd ../kube-ansible
#./tools/setup 

## setup troubleshooting namespace and apps
#### kubectl create --type namespace --name ts
