---

- name: Reset SSL cert
  when: reset_cert|default(false)
  include_tasks: reset-cert.yml

- name: Reset Kubernetes cluster
  when: reset_kubernetes|default(false)
  include_tasks: reset-kubernetes.yml

- name: Reset Etcd cluster
  when: reset_etcd|default(false)
  include_tasks: reset-etcd.yml

- name: Reset Docker registry cluster
  when: reset_registry|default(false)
  include_tasks: reset-registry.yml
