---

- name: Remove generation of SSL cert directory
  file: path="{{ dir.gen_ssl }}" state=absent
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  ignore_errors: True

- name: Remove local of SSL cert directory
  file: path="{{ dir.local_ssl }}" state=absent
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  ignore_errors: True
