---

- name: Stop Etcd systemd service
  systemd: name=etcd state=stopped enabled=no
  ignore_errors: True

- name: Delete Etcd systemd service file
  file: path="{{ systemd.dir.service }}/etcd.service" state=absent
  ignore_errors: True

- name: Delete all Etcd directory
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ etcd.dir.etc }}"
    - "{{ etcd.dir.data }}"
    - "{{ etcd.dir.ssl }}"
    - "{{ downloads.etcd.dir }}"
  ignore_errors: True
