---

- name: Stop all component systemd service
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - docker.service
    - docker.socket
  ignore_errors: True

- name: Delete Docker systemd service file
  file: path="{{ systemd.dir.service }}/{{ item }}" state=absent
  with_items:
    - docker.service
    - docker.socket
  ignore_errors: True

- name: Delete Docker container and registry data
  file: path="{{ item }}" state=absent
  with_items:
    - /var/lib/registry
    - "{{ downloads.docker.dir }}"
  ignore_errors: True
