---
# Require the cluster is fully operation and running

- hosts: kube-addon
  become: yes
  roles:
  - { role: kubernetes/addon, tags: dashboard,  when: kube_dashboard,  addon: "{{ addons.dashboard }}" }
  - { role: kubernetes/addon, tags: logging,    when: kube_logging,    addon: "{{ addons.logging }}" }
  - { role: kubernetes/addon, tags: monitoring, when: kube_monitoring, addon: "{{ addons.monitoring }}" }
  - { role: kubernetes/addon, tags: ingress,    when: ingress,         addon: "{{ addons.ingress[ingress_type] }}" }
