---

- hosts: masters
  become: yes
  tags: reset_cert
  roles:
    - { role: ops/reset , reset_cert: true }

- hosts: "{{ hosts | default('kube-cluster') }}"
  become: yes
  tags: reset_kubernetes
  roles:
    - { role: ops/reset , reset_kubernetes: true }

- hosts: etcds
  become: yes
  tags: reset_etcd
  roles:
    - { role: ops/reset , reset_etcd: true }
