---

- name: Check kubelet service already exists
  stat: path="{{ systemd.dir.service }}/kubelet.service"
  register: check_kubelet_service

- name: Stop kubelet systemd service to upgrade
  when: check_kubelet_service.stat.exists
  service: name=kubelet enabled=yes state=stopped

- name: Configure Kubernetes node component
  when: "ansible_host not in groups['masters']"
  include_tasks: config-node.yml

- name: Add kubelet systemd service
  when: "ansible_host not in groups['masters']"
  include_tasks: config-systemd.yml

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet
