---

- name: Create Kubernetes addon directory
  file: path="{{ kubernetes.dir.addon }}/{{ addon.name }}" state=directory
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: "Copy {{ addon.name }} yml files"
  template:
    src: "{{ addon.name }}/{{ item }}.j2"
    dest: "{{ kubernetes.dir.addon }}/{{ addon.name }}/{{ item }}"
  delegate_to: "{{ groups['masters'][0] }}"
  with_items: "{{ addon['files'] }}"
  run_once: true
  register: copy_addon

- name: Config Kubernetes dashboard
  when: kube_dashboard and addon.name == 'kube-dashboard'
  include_tasks: config-dashboard.yml
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: "Apply {{ addon.name }} addon"
  when: copy_addon
  command: |
    {{ dir.bin }}/kubectl --kubeconfig={{ kubernetes.config.admin }} \
      apply -f {{ kubernetes.dir.addon }}/{{ addon.name }}/{{ item }}
  delegate_to: "{{ groups['masters'][0] }}"
  with_items: "{{ addon['files'] }}"
  run_once: true
  register: apply_addon
  until: apply_addon.rc == 0
  retries: 5
  delay: 2
