---

- name: Etcd configuration
  include_tasks: config-etcd.yml

- name: Add Etcd systemd service
  include_tasks: config-systemd.yml

- name: Enable and restart Etcd
  when: change_etcd
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_etcd
