---
# Ceph cluster on Kubernetes
ceph_version: luminous
ceph:
  tag: "tag-build-master-{{ ceph_version }}-ubuntu-16.04"
  rgw:
    vip: "{{ lb_vip_address }}"
    port: 8080
  rest_api:
    vip: "{{ lb_vip_address }}"
    port: 5000
  osd:
    cluster_net: "{{ pod_network_cidr }}"
    public_net: "{{ pod_network_cidr }}"
