---

config:
  cluster_name: kubernetes
  contexts:
    - name: kubernetes-admin
      context: kubernetes-admin@kubernetes
      ca: "{{ kubernetes.certs.ca }}"
      cert: "{{ kubernetes.certs.admin }}"
      cert_key: "{{ kubernetes.certs.admin_key }}"
      path: "{{ kubernetes.config.admin }}"
    - name: system:kube-controller-manager
      context: system:kube-controller-manager@kubernetes
      ca: "{{ kubernetes.certs.ca }}"
      cert: "{{ kubernetes.certs.controller_manager }}"
      cert_key: "{{ kubernetes.certs.controller_manager_key }}"
      path: "{{ kubernetes.config.controller_manager }}"
    - name: system:kube-scheduler
      context: system:kube-scheduler@kubernetes
      ca: "{{ kubernetes.certs.ca }}"
      cert: "{{ kubernetes.certs.scheduler }}"
      cert_key: "{{ kubernetes.certs.scheduler_key }}"
      path: "{{ kubernetes.config.scheduler }}"
    - name: "system:node:{{ ansible_hostname }}"
      context: "system:node:{{ ansible_hostname }}@kubernetes"
      ca: "{{ kubernetes.certs.ca }}"
      cert: "{{ kubernetes.certs.kubelet }}"
      cert_key: "{{ kubernetes.certs.kubelet_key }}"
      path: "{{ kubernetes.config.kubelet }}"
    - name: system:kube-proxy
      context: system:kube-proxy@kubernetes
      ca: "{{ kubernetes.certs.ca }}"
      cert: "{{ kubernetes.certs.kube_proxy }}"
      cert_key: "{{ kubernetes.certs.kube_proxy_key }}"
      path: "{{ kubernetes.config.kube_proxy }}"
    - name: kubelet-bootstrap
      context: default
      ca: "{{ kubernetes.certs.ca }}"
      token: "{{ bootstrap_token }}"
      path: "{{ kubernetes.config.bootstrap }}"
etcd_keys:
  - 'etcd-ca.pem'
  - 'etcd-ca-key.pem'
  - 'etcd.pem'
  - 'etcd-key.pem'
node_keys:
  node:
    - 'ca.pem'
    - 'ca-key.pem'
  master:
    - 'ca.pem'
    - 'ca-key.pem'
    - 'front-proxy-ca.pem'
    - 'front-proxy-ca-key.pem'
    - 'apiserver.pem'
    - 'apiserver-key.pem'
    - 'scheduler.pem'
    - 'scheduler-key.pem'
    - 'controller-manager.pem'
    - 'controller-manager-key.pem'
    - 'front-proxy-client.pem'
    - 'front-proxy-client-key.pem'
    - 'admin.pem'
    - 'admin-key.pem'
    - 'kube-proxy.pem'
    - 'kube-proxy-key.pem'
    - "kubelet-{{ ansible_hostname }}.pem"
    - "kubelet-{{ ansible_hostname }}-key.pem"
    - 'sa.key'
    - 'sa.pub'
