---

- name: Create Docker system user group
  group:
    name: docker
    state: present

- name: Create Docker system user
  user:
    name: docker
    comment: "Docker user"
    shell: /sbin/nologin
    state: present
    system: yes
    groups: docker

- name: Copy Docker engine service files from host
  template:
    src: "{{ item }}.j2"
    dest: "{{ systemd.dir.service }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - docker.service
    - docker.socket
  register: change_system_service
