---

- name: Enable and restart Docker engine
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker

- name: Write system variables for Kubernetes
  copy:
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables=1
      net.bridge.bridge-nf-call-iptables=1
    dest: /etc/sysctl.d/k8s.conf
  register: copy_sysctl

- name: Enable system variables for Kubernetes
  when: copy_sysctl
  command: "sysctl -p /etc/sysctl.d/k8s.conf"
