dependencies:
  - { role: commons/packages, pkg: "{{ downloads.kubelet }}" }
  - { role: commons/packages, pkg: "{{ downloads.helm }}" }
  - { role: commons/packages, pkg: "{{ downloads.cni }}" }
  - { role: commons/packages, pkg: "{{ downloads.calicoctl }}", when: network == 'calico' or network == 'canal'}
  - { role: commons/container-images, when: cri_plugin =='docker', img: "{{ images.pod_infra }}", pre_pull: false }
  - { role: commons/container-images, when: cri_plugin =='docker', img: "{{ images.manager }}",   pre_pull: false }
  - { role: commons/container-images, when: cri_plugin =='docker', img: "{{ images.scheduler }}", pre_pull: false }
  - { role: commons/container-images, when: cri_plugin =='docker', img: "{{ images.apiserver }}" }
