---

cluster_name: kubernetes
etcd_servers: "{% for node in groups['etcds'] %}https://{{ node }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

admission_controls: Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
preferred_address: InternalIP,ExternalIP,Hostname
authorization_mode: Node,RBAC
controllers: "*,bootstrapsigner,tokencleaner"
leader_elect: true
leader_elect_lease_duration: 15s
leader_elect_renew_deadline: 10s
leader_elect_retry_period: 2s
pod_eviction_timeout: 1m0s
node_monitor_grace_period: 40s
node_monitor_period: 5s
feature_gates:
  controller: RotateKubeletServerCertificate=true
  apiserver: "{% if kube_version.split('.')[1]|int < 8 %}AdvancedAuditing=true{% endif -%}"
  scheduler: ""
