---

- name: Enable the shared IP address variable
  when: keepalived
  command: "{{ item }}"
  with_items:
    - "echo 'net.ipv4.ip_nonlocal_bind=1' > /etc/sysctl.conf"
    - "sysctl -p /etc/sysctl.conf"

- name: Create Kubernetes manifests config directory
  when: keepalived or haproxy
  file: path={{ kubernetes.dir.manifest }} state=directory

- name: Copy Keepalived manifest yaml file
  when: keepalived
  template: src="keepalived.yml.j2" dest={{ kubernetes.dir.manifest }}/keepalived.yml

- name: Create HAProxy config directory
  when: haproxy
  file: path={{ haproxy_etc_dir }} state=directory

- name: Copy HAProxy config file
  when: haproxy
  template: src="haproxy.cfg.j2" dest={{ haproxy_etc_dir }}/haproxy.cfg

- name: Copy HAProxy manifest yaml file
  when: haproxy
  template: src="haproxy.yml.j2" dest={{ kubernetes.dir.manifest }}/haproxy.yml
