---
# Download component task

- name: Override local repository url
  when: 'pkg is defined and repos_offline'
  set_fact:
    bases: >
      {{ bases |
         combine({ pkg.name: {
             'url': repos_offline_url,
             'version': bases[pkg.name]['version']
         }})
      }}

- name: Create download binaries tmp directory
  when: pkg is defined
  file: path="{{ dir.download }}" state=directory

- name: "Create {{ pkg.description }} release directory"
  when: pkg is defined
  file: path="{{ pkg.dir }}" state=directory

- name: Include download archive file
  when: 'pkg is defined and "unarchive" in pkg'
  include_tasks: archive-file.yml

- name: Include download binary file
  when: 'pkg is defined and not "unarchive" in pkg'
  include_tasks: binary-file.yml

- name: Handle containerd pakcages
  when: pkg is defined and pkg.name == 'cri_containerd'
  include_tasks: containerd.yml

- name: "Symlinks {{ pkg.description }} component"
  when: 'pkg is defined and "symlinks" in pkg and pkg_copy'
  file:
    src: "{{ pkg.dir }}/{{ item }}"
    dest: "{{ dir.bin }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ pkg['symlinks'] }}"
