---

- name: Wait for Pod copy CNI config file
  when: cri_plugin == 'containerd'
  shell: "ls {{ kubernetes.dir.cni }} | grep 'conf$' | wc -l"
  register: wait_cni
  until: wait_cni.stdout > 1
  retries: 15
  delay: 6

- name: Delete loopback CNI config
  when: wait_cni and cri_plugin == 'containerd'
  file: path="{{ kubernetes.dir.cni }}/99-loopback.conf" state=absent
  register: delete_lo_conf

- name: Restart CRI Containerd service
  when: delete_lo_conf and cri_plugin == 'containerd'
  systemd:
    name: cri-containerd.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: cri_containerd_restarted
