---

images:
  pod_infra: # registry.access.redhat.com/rhel7/pod-infrastructure
    name: pause
    repos: gcr.io/google_containers/
    tag: "3.0"
  apiserver:
    name: kube-apiserver-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  manager: # 'quay.io/attcomdev/kube-controller-manager:v{{ kube_version }}' for ceph storage class
    name: kube-controller-manager-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  scheduler:
    name: kube-scheduler-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  haproxy:
    name: haproxy
    repos: kairen/
    tag: "1.7"
  keepalived:
    name: keepalived
    repos: kairen/
    tag: "1.2.24"
  registry:
    name: registry
    repos: kairen/
    tag: "2.6.1"
  registry_ui:
    name: docker-registry-ui
    repos: parabuzzle/
    tag: "2.1.3"
  repos:
    name: pkg-repos
    repos: kairen/
    tag: "0.1.0"
